### PR TITLE
[#406] Add symlink in model pods

### PR DESCRIPTION
**Pull request by kirillmakhonin**
This is related to #406

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
Ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
@akharlamov please review

**Comment by akharlamov** [comment]
Approved due time sensitive nature of the PR.

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
failed because of aws rates

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Pull request merged**
