### PR TITLE
[#425] Edi test timeouts increased for the debugging in error cases

### PR DESCRIPTION
**Pull request by ablatov**
Increase tests timeout up to 10 minutes in order to get all stderr from legionctl commands.

### CODE REVIEW

**Comment by ablatov** [comment]
ok to test

**Comment by ablatov** [comment]
@akharlamov legionctl timeout is 5 minutes by default now, maybe it is suitable to set 6 minutes test timeout in order to wait for error logs?

**Comment by kirillmakhonin** [comment]
@ablatov let's set to 6 minutes

**Comment by ablatov** [comment]
ok to test

**Pull request merged**
