### PR TITLE
[#702] Fixed behaviour of default model url

### LINKED ISSUE #702: Disable using of default model_version in case of undefined DEFAULT version choosing algorithm
File: `legion/legion/k8s/enclave.py`
Function: `watch_model_service_endpoints_state` / `normalize_endpoints`

### PR DESCRIPTION
**Pull request by mcdoker18**
Allow a default model URL in case of existing of only one version of a
model. Throw the exception for a user in other cases.

This closes #702

### CODE REVIEW

**Review by kirillmakhonin — DISMISSED** [review]
👍

**Comment by mcdoker18** [comment]
bot, test all

**Comment by mcdoker18** [comment]
bot, test all

**Comment by mcdoker18** [comment]
bot, test all

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test all

**Review by kirillmakhonin — APPROVED** [review]

**Comment by mcdoker18** [comment]
bot, test all

**Review by botsman — APPROVED** [review]

**Review by alexander-semenets — APPROVED** [review]

**Comment by mcdoker18** [comment]
bot, test app

**Pull request merged**
