### PR TITLE
[#577] Bump up kops and kubernetes

### PR DESCRIPTION
**Pull request by MaksymBilenko**
This PR partially solves issue #577 
and soleves issue #567

### CODE REVIEW

**Comment by MaksymBilenko** [comment]
bot, test all

**Comment by MaksymBilenko** [comment]
bot, test all

**Comment by MaksymBilenko** [comment]
bot, test all

**Comment by MaksymBilenko** [comment]
bot, test all

**Comment by MaksymBilenko** [comment]
bot, test all

**Comment by dsuslov** [comment]
@MaksymBilenko please add short comment to 9  deploy/ansible/roles/k8s_create_cluster/defaults/main.yaml why we can use  kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17 with kops 1.10

**Pull request merged**
