### PR TITLE
[#524] update example dag

### PR DESCRIPTION
**Pull request by alexander-semenets**

### CODE REVIEW

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot. test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by aliaksandr-d** [comment]
Two tests failed:

- Check EDI enclave inspect procedure
- Check Edi Multi Versioned Models

**Comment by aliaksandr-d** [comment]
bot, test all

**Pull request merged**
