### PR TITLE
[#452] Update flask version to 0.12.4

### LINKED ISSUE #452: Update version of Flask
We have to update version of Flask to `0.12.3`

### PR DESCRIPTION
**Pull request by kirillmakhonin**
This closes #452

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

Prev run:
```
ASK [legion_core_chart : Attach Airflow S3 accesse policy to the role] ********
failed: [localhost] (item=company-a) => {"changed": true, "enclave": "company-a", "msg": "Rate exceeded"}
	to retry, use: --limit @/var/lib/jenkins/workspace/Deploy_Legion_Release@2/deploy/ansible/deploy-legion.retry
```

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
Is blocked by #455

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by MaksymBilenko** [comment]
ok to test

**Pull request merged**
