### PR TITLE
[#301] Fix log storing in small Jenkins

### PR DESCRIPTION
**Pull request by kirillmakhonin**
It looks like you have tried to train and deploy model from Jenkinsfile that has been placed in the repository root. So, in this case current code works incorrectly and tries to copy log files from one directory to same directory. That is not linked with build number.

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
test this please

**Comment by kirillmakhonin** [comment]
@akharlamov why did you reject this PR? I do not see any comments

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
@akharlamov code has been fixed

**Comment by kirillmakhonin** [comment]
test this please

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
Test summation job failed
```
Archiving artifacts
'/tmp/legion-notebook-run/notebook.html' doesn't match anything: '' exists but not '/tmp/legion-notebook-run/notebook.html'
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: No artifacts found that match the file pattern "/tmp/legion-notebook-run/notebook.html". Configuration error?
Finished: FAILURE
```

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test all

**Pull request merged**
