### PR TITLE
[#196] gunicorn decomission

### LINKED ISSUE #196: Remove gunicorn from list of valid serving workers
remove gunicorn from model serving workers and leave uwsgi as a main worker.
should be removed in base-python-image, tests, default model dockerfile, etc

### PR DESCRIPTION
**Pull request by alexander-semenets**
fixes #196

### CODE REVIEW

**Comment by alexander-semenets** [comment]
ok to test

**Comment by alexander-semenets** [comment]
test this please

**Comment by akharlamov** [comment]
So, do we close it or do we merge it?

**Comment by alexander-semenets** [comment]
Agreed to fix this in #31 in order to simplify merge

**Pull request closed without merging**
