### PR TITLE
[#517] secure helm

### LINKED ISSUE #517: Secure helm/tiller from external abuse.
The default helm configuration in k8s cluster is not secure. Tiller exposes port without auth/auth that can be used for attacks. Read related article https://engineering.bitnami.com/articles/helm-security.html

Apply configuration updates for Helm to close this security hole.

### PR DESCRIPTION
**Pull request by alexander-semenets**
this fixes #517

### CODE REVIEW

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test infra

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test infra

**Review by botsman — APPROVED** [review]

**Review by mcdoker18 — APPROVED** [review]

**Review by kirillmakhonin — APPROVED** [review]

**Pull request merged**
