### PR TITLE
[#161] Trigger Airflow tasks in robot test and check status

### PR DESCRIPTION
**Pull request by leshchanka-aliaksandr**
Airflow API client was enhanced and robot tests was updated to execute Aiflow dags in test mode and wait for a success completion.

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
@leshchanka-aliaksandr does it close #161? Please give more information about this PR

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
```
TASK [legion_enclave : Attach Airflow S3 accesse policy to the role] ***********
fatal: [localhost]: FAILED! => {"changed": true, "msg": "Rate exceeded"}
	to retry, use: --limit @/var/lib/jenkins/workspace/Deploy_Legion_Enclave/deploy/ansible/deploy-legion-enclave.retry

```

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by leshchanka-aliaksandr** [comment]
test this please

**Comment by kirillmakhonin** [comment]
test this please

**Comment by dsuslov** [comment]
test this please

**Comment by dsuslov** [comment]
test this please

**Comment by kirillmakhonin** [comment]
test this please

**Pull request merged**
