### PR TITLE
[#549] Disable Edge home page in Nginx config based on profile parameter

### LINKED ISSUE #549: Add profile parameter to hide Edge home page
Currently Edge home page is not secured, that contains link to Legion github, link to documentation. 
This page visibility should be configured in profile file as an additional parameter.
User should got 404 error if this profile parameter is enabled.

### PR DESCRIPTION
**Pull request by aliaksandr-d**
This PR closes #549 
1. Passed environment variable to Edge pod based on property in profile file
2. Created **os_environ** template plugin
3. Updated nginx.conf template, to read **ENABLE_HOME_PAGE** environment variable
4. Changed Edge liveness probe, because edge home page returns 404 when home page is disabled

### CODE REVIEW

**Comment by aliaksandr-d** [comment]
bot, test all

**Comment by aliaksandr-d** [comment]
bot, test all

**Comment by aliaksandr-d** [comment]
_| Jenkins Build #1 logs: Started by user admin Checking out git ${GitRepository} into /var/jenkins_home/workspace/PERF TEST Vertical-Scaling@script to read examples/Vertical-Scaling/performance.Jenkinsfile Cloning the remote Git repository Cloning repository https://github.com/legion-platform/legion.git  > git init /var/jenkins_home/workspace/PERF TEST Vertical-Scaling@script # timeout=10 Fetching upstream changes from https://github.com/legion-platform/legion.git  > git --version # timeout=10 using GIT_SSH to set credentials   > git fetch --tags --progress https://github.com/legion-platform/legion.git +refs/heads/*:refs/remotes/origin/*  > git config remote.origin.url https://github.com/legion-platform/legion.git # timeout=10  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10  > git config remote.origin.url https://github.com/legion-platform/legion.git # timeout=10 Fetching upstream changes from https://github.com/legion-platform/legion.git using GIT_SSH to set credentials   > git fetch --tags --progress https://github.com/legion-platform/legion.git +refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*  > git rev-parse fe082da1e8154b419bd58ad70a947acc1337589e^{commit} # timeout=10 Checking out Revision fe082da1e8154b419bd58ad70a947acc1337589e (detached)  > git config core.sparsecheckout # timeout=10  > git checkout -f fe082da1e8154b419bd58ad70a947acc1337589e Commit message: "Merge 13041ade7834d9349d5b292bfc5acbf72570aef4 into 426ce6c54891e9fb19323877a026df4742140037" First time build. Skipping changelog. Running in Durability level: MAX_SURVIVABILITY [Pipeline] node Running on Jenkins in /var/jenkins_home/workspace/PERF TEST Vertical-Scaling [Pipeline] { [Pipeline] legion [Pipeline] load [Pipeline] { (/var/jenkins_home/jobs/PERF TEST Vertical-Scaling/builds/1/scripts/legion.groovy) [Pipeline] } [Pipeline] // load [Pipeline] podTemplate [Pipeline] { [Pipeline] node Still waiting to schedule task There are no nodes with the label ‘jenkins-build-9d6d66bb-5c7c-45fa-afff-ab6f64eee1ab’ |  
-- | -- | --_

**Comment by aliaksandr-d** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
@aliaksandr-d , this PR is'n compatible with #550

**Pull request merged**
