### PR TITLE
[#802] add cache pull as a function

### LINKED ISSUE #802: Add function for updating docker cache in CI Jenkinsfile
Please replace 
```

sh """
docker pull grafana/grafana:4.5.0
docker pull ${env.param_docker_registry}/k8s-grafana:${env.param_docker_cache_source} || true
"""
```
with
```
updateDockerCache('grafana/grafana:4.5.0', 'k8s-grafana')

def updateDockerCache(base_image=null, legion_image=null){
    if (base_image){
        sh "docker pull ${base_image}"
    }
    if (legion_image){
        //......
        sh "docker pull ${env.param_docker_registry}/${legion_image}:${env.param_docker_cache_source} || true"
    }
}
```

### PR DESCRIPTION
**Pull request by alexander-semenets**
this fixes #802

### CODE REVIEW

**Comment by alexander-semenets** [comment]
bot, test infra

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test infra

**Review by botsman — APPROVED** [review]

**Review by mcdoker18 — APPROVED** [review]

**Review by kirillmakhonin — APPROVED** [review]

**Pull request merged**
