### PR TITLE
[#887] Replace jupyter with jupyterlab

### LINKED ISSUE #887: Replace jupyter with jupyterlab in python toolchain
As user I want to have ability to work with files in many windows inside browser window and to have console

### LINKED ISSUE #890: Add ability to gather and analyze metrics in local mode
As a user of Legion's local mode, I want to view all metrics that my model has sent.

As an additional functionality I want to see my metrics on a cluster, even I've trained model locally.

It should be easily to view this metric (e.g. using jupyter's plugin)

### PR DESCRIPTION
**Pull request by kirillmakhonin**
* Replaced jupyter with jupyterlab in python toolchain image
* Added `workDir` parameter of model training CRD
* Added robot tests for `workDir`
* Added ability to gather and analyze metrics in local mode 
* Added usage of `model.show_metrics` in all legion toolchain examples
* Added training of `Sklearn-Income` example in robot tests 

This closes #887
This closes #890

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test app

**Review by mcdoker18 — DISMISSED** [review]

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test app

**Review by alexander-semenets — DISMISSED** [review]

**Comment by mcdoker18** [comment]
bot, test app

**Review by mcdoker18 — APPROVED** [review]

**Review by alexander-semenets — APPROVED** [review]

**Pull request merged**
