### PR TITLE
[#825] restore build version format

### LINKED ISSUE #825: Restore Build_id in artifact version

### PR DESCRIPTION
**Pull request by alexander-semenets**
this fixes #825 
- build_id moved back to version string

### CODE REVIEW

**Comment by alexander-semenets** [comment]
bot, test app

**Review by mcdoker18 — DISMISSED** [review]

**Review by botsman — DISMISSED** [review]

**Review by kirillmakhonin — DISMISSED** [review]

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Review by mcdoker18 — APPROVED** [review]

**Review by kirillmakhonin — APPROVED** [review]

**Pull request merged**
