### PR TITLE
[#518] [#511] Scale down node after vertical scaling test

### PR DESCRIPTION
**Pull request by ablatov**
Now we get nodes count before test -> 
request resources for new node creation -> 
check that new node was created -> 
check that new node was scaled down (7 min timeout, every 5 sec check)

### CODE REVIEW

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by MaksymBilenko** [comment]
Closed in favor of #522

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by MaksymBilenko** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test infra

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test infra

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Pull request merged**
