### PR TITLE
[#334][#345] Legionctl tests with '*' param added to check multiple models actions

### PR DESCRIPTION
**Pull request by ablatov**
In this PR:
1. Tests added: 
- scale by id=* and by (id=id versions=*)
- undeploy by id=* and by (id=id + versions=*)
- inspect id=* and by (id=id versions=*)
2. Fixed legionctl behavior with such tests.

### CODE REVIEW

**Comment by ablatov** [comment]
ok to test

**Comment by ablatov** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by ablatov** [comment]
ok to test

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Pull request closed without merging**
