### PR TITLE
[#378] Fixed Dex configurations for empty Dex connectors

### PR DESCRIPTION
**Pull request by aliaksandr-d**
1. Fixed Dex configuration template, for cases when no Dex connectors are defined
2. Removed Airflow check as it's invalid after Dex setup

### CODE REVIEW

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
It has been tested manually on cluster.

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
Waiting for fixes from #411

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
Pulled fixes from develop. Waiting for test results.

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
Tests failed on Airflow part. Restarting CI.

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
secret file was updated on CI cluster

**Comment by aliaksandr-d** [comment]
ok to test

**Pull request merged**
