### PR TITLE
[#778] Fix grafana graphs not displaying data

### LINKED ISSUE #778: Model grafana metric are not updating
After calling a model, only `Queries / second` metric updates.
Other metrics show `No data points`

### PR DESCRIPTION
**Pull request by botsman**
This closes #778 

- change statsd config file name

### CODE REVIEW

**Comment by botsman** [comment]
Metrics example
image

**Comment by botsman** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Review by mcdoker18 — APPROVED** [review]

**Review by kirillmakhonin — APPROVED** [review]

**Review by mcdoker18 — APPROVED** [review]

**Comment by botsman** [comment]
bot, test all

**Comment by mcdoker18** [comment]
bot, test all

**Review by alexander-semenets — APPROVED** [review]

**Comment by botsman** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Pull request merged**
