### PR TITLE
[#450] Add Kubernetes resource limits

### LINKED ISSUE #450: Add resource limitations/requests for K8S Pods
Currently we have not resource requests for all k8s pods. So to prevent failures during pods allocation and execution on k8s cluster: 1) update default shape types and its number 2) define resource limits for pods.

### PR DESCRIPTION
**Pull request by alexander-semenets**
this fixes #450

### CODE REVIEW

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
👍

**Pull request merged**
