### PR TITLE
Remove unused docker and kubernetes labels

### PR DESCRIPTION
**Pull request by kirillmakhonin**

### CODE REVIEW

**Comment by alexander-semenets** [comment]
test this please

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
@akharlamov please review

**Pull request merged**
