### PR TITLE
[#860] legion tests on GKE

### PR DESCRIPTION
**Pull request by alexander-semenets**
- add fluend support for gcs buckets
- add gcloud to agent container
- fix edge build issue

### CODE REVIEW

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test app

**Review by mcdoker18 — APPROVED** [review]

**Comment by alexander-semenets** [comment]
bot, test gcp infra

**Review by karbyshevds — APPROVED** [review]

**Comment by alexander-semenets** [comment]
bot, test gcp infra

**Comment by alexander-semenets** [comment]
bot, test gcp infra

**Pull request merged**
