### PR TITLE
[#312] Update Kubernetes API package to 6.0.0 version

### LINKED ISSUE #312: Update to kubernetes 6.0.0 in order to support Python 3.7
In current kubernetes Python package there is a param named `async` that is invalid for Python 3.7, but valid for Python 3.6. Way to solve: update kuberenetes package to version 6.0 in requirements

### PR DESCRIPTION
**Pull request by leshchanka-aliaksandr**
This closes #312

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
test failed due to bugs in develop, please restart CI on stable develop

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test all

**Pull request merged**
