### PR TITLE
[#475] Remove sleeps in regression tests

### LINKED ISSUE #475: Remove sleeps in regression tests

### PR DESCRIPTION
**Pull request by kirillmakhonin**
This closes #475

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
test this please

**Comment by kirillmakhonin** [comment]
test this please

**Comment by kirillmakhonin** [comment]
test this please

**Comment by kirillmakhonin** [comment]
Test've got an error during airflow testing: 
```
OSError: Authentication endpoint is unavailable, got 503 http code
```

test this please

**Comment by kirillmakhonin** [comment]
test this please

**Comment by kirillmakhonin** [comment]
test this please

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test app

**Pull request merged**
