### PR TITLE
[#349] Fix kubectl context selection

### LINKED ISSUE #349: Kubectl context missed in ansible role tasks

### PR DESCRIPTION
**Pull request by alexander-semenets**
This closes #349

### CODE REVIEW

**Comment by alexander-semenets** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
@akharlamov please approve

**Comment by akharlamov** [comment]
“Fix context” how descriptive :) Did we really have not time to write a proper commit desc?

**Comment by kirillmakhonin** [comment]
test this please

**Pull request merged**
