### PR TITLE
Custom profiles and shared pipeline methods

### LINKED ISSUE #180: Allow shared usage and remove duplicates in jenkins pipelines

### PR DESCRIPTION
**Pull request by MaksymBilenko**
This PR fixes #180 #181

### CODE REVIEW

**Comment by MaksymBilenko** [comment]
ok to test

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by alexander-semenets** [comment]
LGTM

**Pull request merged**
