### PR TITLE
[#323] Legion components authorization tests added

### PR DESCRIPTION
**Pull request by ablatov**
**Three tests group added:**
- check the presence of the auth
- check invalid auth
- check valid auth
**Current tests covers:**
Jenkins, Nexus, Grafana(cluster and enclave), Flower, Airflow

### CODE REVIEW

**Comment by ablatov** [comment]
ok to test

**Comment by ablatov** [comment]
ok to test

**Comment by akharlamov** [comment]
test

**Comment by ablatov** [comment]
ok to test

**Pull request merged**
