### PR TITLE
[773] fix Sklearn-income test

### LINKED ISSUE #773: Fix Sklearn-Income test authorization
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/DYNAMIC MODEL Sklearn-Income/examples/Sklearn-Income/tests/test_basic.py", line 44, in test_model
    "workclass": "Private"
  File "/usr/local/lib/python3.6/dist-packages/legion/model/client.py", line 273, in invoke
    return self._parse_response(response)
  File "/usr/local/lib/python3.6/dist-packages/legion/model/client.py", line 190, in _parse_response
    .format(response.status_code, data, url))
Exception: Wrong status code returned: 401. Data: <html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty/1.13.6.2</center>
</body>
</html>
```

Probably fixing model version is enough. (1.0 to 1.1)

### PR DESCRIPTION
**Pull request by skayerok**
This closes #773 

Fix model version when generationg JWT

### CODE REVIEW

**Comment by skayerok** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Comment by botsman** [comment]
bot, test all

**Pull request merged**
