### PR TITLE
[#759] Use escaped_request_uri to pass redirect url to Oauth Proxy

### LINKED ISSUE #759: URL parameters are lost after authorization
Steps to reproduce:
1. Open incognito tag
2. Open any cluster service URL with multiple parameters (e.g. https://airflow-company-a.***/admin/airflow/tree?dag_id=salesforce_fetcher_all&num_runs=25 )
3. Authorization form appears
4. Authorize
5. After redirect check URL in address bar, it's different - second parameter disappear.

### PR DESCRIPTION
**Pull request by aliaksandr-d**
This PR closes #759 
**escaped_request_uri** variable was created and used for redirect url creation.

### CODE REVIEW

**Review by mcdoker18 — DISMISSED** [review]

**Comment by mcdoker18** [comment]
bot, test all

**Review by botsman — DISMISSED** [review]

**Comment by botsman** [comment]
bot, test all

**Comment by mcdoker18** [comment]
bot, test all

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test all

**Comment by alexander-semenets** [comment]
bot, test all

**Review by kirillmakhonin — APPROVED** [review]

**Comment by mcdoker18** [comment]
bot, test all

**Review by mcdoker18 — APPROVED** [review]

**Review by botsman — APPROVED** [review]

**Comment by mcdoker18** [comment]
bot, test all

**Review by kirillmakhonin — APPROVED** [review]

**Comment by mcdoker18** [comment]
bot, test all

**Comment by mcdoker18** [comment]
bot, test all

**Pull request merged**
