### PR TITLE
[#358] Fixes model_id variable name in 2 tests

### PR DESCRIPTION
**Pull request by ablatov**
Fixes misspelling of the test variable.

### CODE REVIEW

**Comment by ablatov** [comment]
ok to test

**Comment by ablatov** [comment]
ok to test

**Comment by ablatov** [comment]
ok to test

**Comment by ablatov** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
@ablatov need to be rebased due to new release mechanism

**Comment by ablatov** [comment]
ok to test

**Pull request merged**
