### PR TITLE
[#684] Fixed disabling of cache in the build job

### LINKED ISSUE #684: CI Job Build Artifacts always uses docker cache. Disabling is not working

### PR DESCRIPTION
**Pull request by mcdoker18**
Need to convert the variable to boolean type before a comparison
This closes #684

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
@dsuslov please approve

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by mcdoker18** [comment]
bot, test all

**Comment by mcdoker18** [comment]
Close this PR because it is duplicate of #678

**Pull request closed without merging**
