### PR TITLE
Fix tests for custom profiles location

### PR DESCRIPTION
**Pull request by MaksymBilenko**
Add support of custom profiles location at test phase

### CODE REVIEW

**Comment by MaksymBilenko** [comment]
ok to test

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by aliaksandr-d** [comment]
IMHO there are several similar names variables , that can be confusing:
- PROFILES_PATH
- PATH_TO_PROFILES
- PATH_TO_PROFILE
Other changes look good for me.

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Pull request merged**
