### PR TITLE
[#583] Flower scale up and down tests fixed

### LINKED ISSUE #583: Make Flower tests to wait for started workers
Now Flower tests failed with workers count = 0 because we do not wait for their start properly.

### PR DESCRIPTION
**Pull request by ablatov**
This closes #583

### CODE REVIEW

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
@ablatov why did you copy paste code for timed-iterations? We already have such utilitary functions in `legion` and `legion_test` packages

**Comment by ablatov** [comment]
bot, test all

**Pull request merged**
