### PR TITLE
[#693] Replace test tags with default tags and add the "apps" tag

### LINKED ISSUE #693: Apps tests don't launch the "6_incorrect_legionctl_commands" test suite

### PR DESCRIPTION
**Pull request by mcdoker18**
This closes #693

### CODE REVIEW

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
bot, test app

**Comment by mcdoker18** [comment]
Bot, test app

**Comment by dsuslov** [comment]
bot, test app

**Comment by dsuslov** [comment]
bot, test all

**Pull request merged**
