### PR TITLE
[#136] Add refspec for PR builder to Model jobs

### LINKED ISSUE #136: Update Legion model jobs with new refspec
In order to be able to run CI build job which tests PRs we should be able to checkout merge commits produced by PR Builder plugin. For now we are missing a refspec which covers those commit hashes:
+refs/pull/*:refs/remotes/origin/pr/* at model (so called small) jenkins 
So resulting refspec for all jobs will look like:
 +refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*
This might be achieved by increasing functionality of create_example_jobs script with new refspec parameter.

### PR DESCRIPTION
**Pull request by alexander-semenets**
This PR resolves #136 issue
Do not merge! Testing CI on this job right now.

### CODE REVIEW

**Comment by alexander-semenets** [comment]
ok to test

**Comment by MaksymBilenko** [comment]
Why xml template, why not Jenkins Job DSL?

**Comment by kirillmakhonin** [comment]
@MaksymBilenko because of the need to create jobs from some template with substitutions remotely

**Comment by alexander-semenets** [comment]
test this please

**Comment by alexander-semenets** [comment]
test this please

**Comment by alexander-semenets** [comment]
test this please

**Comment by alexander-semenets** [comment]
test this please

**Comment by alexander-semenets** [comment]
test this please

**Pull request merged**
