### PR TITLE
[#521] Fixed CSV reader to read rows cells with commas and quotes

### LINKED ISSUE #521: Airflow S3 operator creates invalid CSV files
Airflow S3 operator creates invalid CSV files in S3, that contains different numbers of columns per rows.

### PR DESCRIPTION
**Pull request by aliaksandr-d**
This PR closes #521 .
Fixed CSV reader to read rows cells with commas and quotes

### CODE REVIEW

**Comment by aliaksandr-d** [comment]
This code has been tested in a cluster

**Comment by aliaksandr-d** [comment]
bot, test all

**Comment by aliaksandr-d** [comment]
bot test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by leshchanka-aliaksandr** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test app

**Pull request merged**
