### PR TITLE
Enable dex auth on enclave grafana ingress

### PR DESCRIPTION
**Pull request by MaksymBilenko**
This PR enables Dex auth on enclave grafana when dex is enabled

### CODE REVIEW

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by akharlamov** [comment]
Is it WIP ?

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
test this please

**Comment by MaksymBilenko** [comment]
Work is done,
Grafana tests are passing

**Pull request merged**
