### PR TITLE
[#667] Remove legion-template plugin file_monitor

### LINKED ISSUE #667: Remove file_change_monitor plugin of legion-template
We've added this plugin to legion-template to have an opportunity to re-render target file when monitored files change. But currently we've removed this functionality (that relies on files) and switched to direct K8S Config Map monitoring through K8S API (e.g. `enclave_configmap_monitor`).

I guess we have to remove this redundant part because it is not very reliable (it relies on io events).

### PR DESCRIPTION
**Pull request by kirillmakhonin**
This closes #667

### CODE REVIEW

**Comment by kirillmakhonin** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
bot, test app

**Comment by alexander-semenets** [comment]
bot, test app

**Comment by kirillmakhonin** [comment]
bot, test all

**Pull request merged**
