### PR TITLE
[#443] Modified Airflow worker permissions to enable ConfigMap creation

### LINKED ISSUE #443: Airflow worker unable to create ConfigMap
When trying to create ConfigMap from inside the Airflow and then list the results (using legion.k8s.K8SConfigMapStorage.list) you will get an error:
`HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 10 Sep 2018 12:57:59 GMT', 'Content-Length': '298'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:company-a:airflow-company-a-airflow-worker\" cannot list configmaps in the namespace \"company-a\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}`

### PR DESCRIPTION
**Pull request by torquerrr**
Added appropriate permissions to Airflow worker so it will be able to create and save ConfigMaps.
This PR closes #443

### CODE REVIEW

**Comment by aliaksandr-d** [comment]
Ok to test

**Comment by kirillmakhonin** [comment]
```
ASK [aws_resources : Create Airflow Postgres RDS instance] ********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Timeout waiting for RDS resource legion-ci-airflow-rds"}
	to retry, use: --limit @/var/lib/jenkins/workspace/Create_cluster/deploy/ansible/create-cluster.retry
```

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
```
Downloading plugin: favorite-plugin from https://updates.jenkins.io/download/plugins/favorite-plugin/2.3.2/favorite-plugin.hpi

Failed to download plugin: favorite or favorite-plugin

```

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
Need to rework role mapping. Please, add regular expression for a configmap and secrets names, check if other configmaps and secrets are unavailable, also please check the restrictions for configmaps in other namespaces.

**Comment by aliaksandr-d** [comment]
@kirillmakhonin
Looks like it's forbidden to use *asterisk* in *resourceNames* field in K8s Role.
Also rule in K8s Role doesn't support any labels selectors. We should specify an exact list of configmaps or secrets.
https://github.com/kubernetes/kubernetes/issues/56582#issuecomment-411068578
If you have another solution, please, let me know.

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
```

TASK [legion_enclave : Attach Airflow S3 accesse policy to the role] ***********
fatal: [localhost]: FAILED! => {"changed": true, "msg": "Rate exceeded"}
	to retry, use: --limit @/var/lib/jenkins/workspace/Deploy_Legion_Enclave/deploy/ansible/deploy-legion-enclave.retry

```

**Comment by aliaksandr-d** [comment]
ok to test

**Comment by aliaksandr-d** [comment]
```
Check EDI scale up procedure :: Try to scale up model through EDI ... 
2018-09-19 08:30:03,109 - INFO - Some hanging processes have been detected for failed test 'Check EDI scale up procedure'

2018-09-19 08:30:03,109 - INFO - Killing active process 'legionctl --verbose scale demo-abc-model 2 --edi https://edi-company-a.legion-ci.epm.kharlamov.biz --user admin --password admin' for test 'Check EDI scale up procedure' because of 'Test timeout 6 minutes exceeded.'

2018-09-19 08:30:03,109 - DEBUG - Killing process #10362

2018-09-19 08:30:13,110 - ERROR - Cannot gather process #10362 logs: ExecutionTimeoutException()
/var/lib/jenkins/workspace/Deploy_Legion_Release/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/var/lib/jenkins/workspace/Deploy_Legion_Release/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[ ERROR ] Cannot gather process #10362 logs: ExecutionTimeoutException()
| FAIL |
Test timeout 6 minutes exceeded.
```

**Comment by aliaksandr-d** [comment]
ok to test

**Pull request merged**
