### PR TITLE
[#563] API token per model

### LINKED ISSUE #563: Generate API token per model
Add a possibility to generate and check API tokens per model

### PR DESCRIPTION
**Pull request by leshchanka-aliaksandr**
This closes #563

### CODE REVIEW

**Comment by leshchanka-aliaksandr** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
bot, test all

**Comment by kirillmakhonin** [comment]
bot, test all

**Comment by ablatov** [comment]
Test setup "Run EDI deploy and check model started" failed twice because of cluster network problems.
Restart.

**Comment by ablatov** [comment]
bot, test all

**Comment by ablatov** [comment]
Test setup "Run EDI deploy and check model started". Network cluster problem again. Restart.

**Comment by ablatov** [comment]
`Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/bin/legionctl", line 154, in <module>
    args.func(args)
  File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/edi/deploy.py", line 299, in deploy_kubernetes
    args.readinesstimeout)
  File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/external/edi.py", line 184, in deploy
    return self.parse_deployments(self._query(legion.edi.server.EDI_DEPLOY, action='POST', payload=payload))
  File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/external/edi.py", line 112, in _query
    raise Exception('Got error from server: {!r}'.format(exception))
Exception: Got error from server: 'Cannot find deployment for model service <bound method ModelService.__str__ of ModelService for model demo-abc-model version 1.0>'    
16:45:54.789    INFO    ${resp} = <result object with rc 2>`

**Comment by ablatov** [comment]
@kirillmakhonin very strange error that appeared after 1 pm.

**Comment by ablatov** [comment]
bot, test app

**Comment by aliaksandr-d** [comment]
bot, test all

**Comment by aliaksandr-d** [comment]
bot, test all

**Comment by aliaksandr-d** [comment]
*Check if flower scale down works properly* test failed.
`

  | Expected ready workers count '1' does not match actual '2'
-- | --

`

**Comment by aliaksandr-d** [comment]
bot, test all

**Pull request merged**
