### PR TITLE
[#112] Add Kube ELB security plugin deployment

### PR DESCRIPTION
**Pull request by MaksymBilenko**
Build of a plugin would be moved to this repo on separate PR

### CODE REVIEW

**Comment by MaksymBilenko** [comment]
ok to test

**Comment by kirillmakhonin** [comment]
@MaksymBilenko please rebase onto develop due to new release mechanism

**Comment by MaksymBilenko** [comment]
ok to test

**Comment by MaksymBilenko** [comment]
ok to test

**Comment by MaksymBilenko** [comment]
ok to test

**Comment by MaksymBilenko** [comment]
@akharlamov as m mentioned on top - moving of sources would be made on next PR

**Comment by MaksymBilenko** [comment]
@akharlamov and we need to have this urgently...
Due to possible issues with automated tests codebase would be moved on next PR

**Comment by MaksymBilenko** [comment]
ok to test

**Pull request merged**
